export const ADD_COUNTER = 'ADD_COUNTER';
export const REMOVE_COUNTER = 'REMOVE_COUNTER';
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const UPDATE_MARKERS = 'UPDATE_MARKERS';
export const UPDATE_GEO_PARAMS = 'UPDATE_GEO_PARAMS';
