export const ADD_COUNTER = 'ADD_COUNTER';
export const REMOVE_COUNTER = 'REMOVE_COUNTER';
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const UPDATE_MARKERS = 'UPDATE_MARKERS';
export const UPDATE_ACTIVE_MARKER_KEY = 'UPDATE_ACTIVE_MARKER_KEY';
export const UPDATE_GEO_PARAMS = 'UPDATE_GEO_PARAMS';
export const UPDATE_REACT_SELECT_SELECTED_OPTION = 'UPDATE_REACT_SELECT_SELECTED_OPTION';
export const UPDATE_MAP_STATE = 'UPDATE_MAP_STATE';
